image: rustlang/rust:nightly

pipelines:
  default:
    - step:
        caches:
          - cargo
          - rust-target
        script:
          - echo "Build project"  ; cargo build --release
          - echo "Run unit tests" ; cargo test --release -v --no-fail-fast -- --nocapture --test
definitions:
  caches:
    cargo: /usr/local/cargo # CARGO_HOME
    rust-target: $BITBUCKET_CLONE_DIR/target
