image:
  name: registry.theoplayer.com/rust:1.55
  username: $THEO_DOCKER_USERNAME
  password: $THEO_DOCKER_PASSWORD
  email: docker@theoplayer.com

definitions:
  caches:
    rust: rust-cache
  steps:
    - step: &build
        name: Build
        caches:
          - rust
        script:
          - ./scripts/extract-cache.sh
          - cargo build --workspace --release --all-targets
          - ./scripts/build-cache.sh
    - step: &test
        name: Test
        caches:
          - rust
        script:
          - ./scripts/extract-cache.sh
          - cargo test --release --no-fail-fast --all-targets --workspace -- --nocapture --test
          - ./scripts/build-cache.sh
    - step: &checks
        name: Checks
        caches:
          - rust
        script:
          - ./scripts/extract-cache.sh
          - cargo clippy --release --all-targets --workspace -- -D warnings
          - cargo fmt --all -- --check
          - ./scripts/build-cache.sh

pipelines:
  default:
    - step: *build
    - step: *test
  pull-requests:
    "**":
      - step: *checks
  tags:
    v*:
      - step: *build
      - step: *checks
      - step:
          name: Publish
          caches:
            - rust
          script:
            - ./scripts/extract-cache.sh
            - cargo publish
